name: Deploy Node.js App to Azure VM

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  VM_USERNAME: azureuser  # Replace with your actual VM username

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive project files
        run: zip -r backend.zip . -x "*.git*"

      - name: Copy files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ env.VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "backend.zip"
          target: "~/"

      - name: SSH into Azure VM and deploy app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ env.VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y unzip
            rm -rf ~/backend-app
            unzip -o ~/backend.zip -d ~/backend-app
            mkdir ~/backend-app
            cd ~/backend-app
            npm install
            pm2 delete backend || true
            pm2 start src/index.js --name backend
